apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTmpJMU1EazJOVGt3SGhjTk1qVXhNVEEzTVRBd01EVTVXaGNOTXpVeE1UQTFNVEF3TURVNQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTmpJMU1EazJOVGt3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRWXBUa0xVYUFCYmFVTmYxR1FvK3ZoU2M3ZnhVWk1PV2V1MXd1R1pBTW0KSENhSzY2SHBPejFWeGZIeGVsMUlSbTloNTQvQzJTdEVldUNKRWx3Q0NlRHZvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVTZtcHk4OUFpUTNreHcxbi9XRFNECnRoSHcvNkF3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQUxScUhuWVhUY0NOQ3FXdnJGVDBEbno0ZC81NEVuVlYKb3RIWm5Kd3Vrd2tJQWlFQW00MVpkQnE3bmlybldWU280Q3NVYkdTQWRuUS9WazI5VnFOZkI1RC9wS1E9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://192.168.66.221:6443
  name: default
contexts:
- context:
    cluster: default
    user: marc
  name: marc@k3s
current-context: marc@k3s
kind: Config
preferences: {}
users:
- name: marc
  user:
    client-certificate: /home/marc/.kube/marc.crt
    client-key: /home/marc/.kube/marc.key