---
- name: Install basic packages
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    state: present
    update_cache: yes

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Harden SSH configuration
  ansible.builtin.copy:
    src: sshd-hardening.conf
    dest: /etc/ssh/sshd_config.d/99-homelab.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload SSH

- name: Configure firewall if enabled
  ansible.builtin.include_tasks: firewall.yaml
  when: firewall_enabled