---
- name: Validate SSH configuration
  ansible.builtin.command:
    cmd: /usr/sbin/sshd -t
  changed_when: false
  listen: Reload SSH

- name: Reload SSH
  ansible.builtin.service:
    name: ssh
    state: reloaded
  listen: Reload SSH